### ISSUE TITLE
Can't open FITS generated by Maxim-DL

### ISSUE THREAD

**Issue by evgenykurbatov** [spacetelescope/PyFITS#103]
Hello everyone!
I'm using PyFITS 3.2.2. The message is:

    .... line 504, in _fromfile_internal
        raise IOError('Header missing END card.')
    IOError: Header missing END card.

The problem actually arises in `_find_end_card` function of `header.py`: when it's iterating over `HEADER_END_RE.finditer(block)` iterator it fails to pass thru the first `if` statement as `mo.start()` is 2209 and `mo.start() % card_len` is 49.

Note that `fitsverify` said this FITS malformed. SAO `ds9` was also unable to open it. However, I have to work with the given stuff. I'm absolutely not familiar with FITS format but I suspect the problem is in Maxim-DL. As this package is widely used maybe there is a workaround for such weird FITSes?

Thanks in advance!

**Comment by evgenykurbatov** [comment]
The problem was solved.  There was mysterious bug we can't reproduce. Attribute it to a cosmic particle. Thanks for the lib!

**Comment by embray** [comment]
Sounds like an actually corrupt FITS file.  PyFITS can often read corrupt files pretty well, but not in all cases.

By the way, are you aware that PyFITS the stand-alone package is being slowly deprecated / subsumed by [http://www.astropy.org](Astropy)?
