### ISSUE TITLE
Writing radio interferometric data

### ISSUE THREAD

**Issue by nirujmohan** [spacetelescope/PyFITS#104]
I read in radio interferometric uv FITS data and would like to write it out after modifications. However, even I write without changing anything ...

```
> fn = pyfits.open('filename.fits')
> fn
[<pyfits.core.GroupsHDU at 0x3eebed0>,
 <pyfits.core.BinTableHDU at 0x3efb710>,
 <pyfits.core.BinTableHDU at 0x3efb690>,
 <pyfits.core.BinTableHDU at 0x3eebb10>]

> fn.writeto('newfile.fits')
```

I get the following error : 

```
/home/user/python/lib32/pyfits/rec.pyc in array(obj, dtype, shape, offset, strides, formats, names, titles, aligned, byteorder, copy)
    559     elif formats is not None:
    560         dtype = format_parser(formats, names, titles,
--> 561                               aligned, byteorder)._descr
    562     else:
    563         kwds = {'formats': formats,

/home/user/python/lib32/pyfits/rec.pyc in __init__(self, formats, names, titles, aligned, byteorder)
     51         self._parseFormats(formats, aligned)
     52         self._setfieldnames(names, titles)
---> 53         self._createdescr(byteorder)
     54 
     55     def _parseFormats(self, formats, aligned=0):

/home/user/python/lib32/pyfits/rec.pyc in _createdescr(self, byteorder)
    125                           'formats':self._f_formats,
    126                           'offsets':self._offsets,
--> 127                           'titles':self._titles})
    128         if (byteorder is not None):
    129             byteorder = _byteorderconv[byteorder[0]]

TypeError: data type not understood
```

What is the correct way of doing this ?

regards
Niruj

**Comment by nirujmohan** [comment]
Sorry, the output of listing fn contents did not parse correctly. I get
fn as a list of 4 elements, viz
<pyfits.core.GroupsHDU at 0x3eebed0>,
 <pyfits.core.BinTableHDU at 0x3efb710>,
 <pyfits.core.BinTableHDU at 0x3efb690>,
 <pyfits.core.BinTableHDU at 0x3eebb10>

**Comment by nirujmohan** [comment]
The output of 
> fn
doesnt seem to come on the screen ... it is a basically a list of 4 elements a GroupsHDU, and 3 BinTableHDUs.

thanks, N.

**Comment by embray** [comment]
This looks like a very old version of pyfits.  The most recent version of [PyFITS](http://www.stsci.edu/institute/software_hardware/pyfits) is v3.3.0.  You can check this by looking at
```python
>>> pyfits.__version__
```
It should also be noted that for all intents and purposes PyFITS has been superseded by [`astropy.io.fits`](http://docs.astropy.org/en/stable/io/fits/index.html), though there should be one more release of PyFITS at some point.

**Comment by nirujmohan** [comment]
Thanks ! Moving to pyfits 3.3 (or to astropy) fixed the problem.
