### ISSUE TITLE
pyfits tests fail with numpy 1.10

### ISSUE THREAD

**Issue by sergiopasra** [spacetelescope/PyFITS#105]
I'm testing 3.3 with numpy 1.10 and there are several errors, namely in

pyfits.tests.test_checksum.TestChecksumFunctions.test_ascii_table_data
pyfits.tests.test_checksum.TestChecksumFunctions.test_binary_table_data
pyfits.tests.test_checksum.TestChecksumFunctions.test_compressed_image_data_float32
pyfits.tests.test_checksum.TestChecksumFunctions.test_compressed_image_data_int16
pyfits.tests.test_checksum.TestChecksumFunctions.test_groups_hdu_data
"Regression test for https://aeon.stsci.edu/ssb/trac/pyfits/ticket/148, part"
pyfits.tests.test_checksum.TestChecksumFunctions.test_variable_length_table_data
"Regression test for"
"Regression test for https://aeon.stsci.edu/ssb/trac/pyfits/ticket/201"
"A simple test of the dump/load methods; dump the data, column, and"
"Tests loading a table dump with no supplied coldefs or header, so that"
"Tests creating a new FITS_rec object from a multi-field ndarray."
"pyfits.tests.test_table.TestTableFunctions.test_new_table_from_recarray"
" pyfits.tests.test_table.TestTableFunctions.test_string_column_padding"

**Comment by embray** [comment]
That's to be expected. I haven't ported updates to `astropy.io.fits` over to pyfits in over a year.
