### ISSUE TITLE
pyfits-3.4 breaks pywcs

### ISSUE THREAD

**Issue by olebole** [spacetelescope/PyFITS#107]
When running the pywcs tests (on Debian), I get several failures due to `pyfits.CardList` missing, like:

```
ERROR: pywcs.tests.test_pickle.test_basic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/pywcs/tests/test_pickle.py", line 23, in test_basic
    s = pickle.dumps(wcs)
  File "/usr/lib/python2.7/dist-packages/pywcs/core.py", line 1259, in __reduce__
    hdulist = self.to_fits(relax=True)
  File "/usr/lib/python2.7/dist-packages/pywcs/core.py", line 1136, in to_fits
    header = self.to_header(relax=relax, wkey=wkey)
  File "/usr/lib/python2.7/dist-packages/pywcs/core.py", line 1223, in to_header
    cards = pyfits.CardList()
AttributeError: 'module' object has no attribute 'CardList'
```

Full test log [here](https://ci.debian.net/data/packages/unstable/amd64/p/python-pywcs/20160205_134201.autopkgtest.log.gz).
I know, `pyfits.CardList` was marked as deprecated in 3.3, and explicitly mentioned that 3.3 is the latest version that supports it; and pywcs is probably hopelessly outdated now as well (not mentioned anymore on the STScI web page), it still has [a number of users](https://qa.debian.org/popcon.php?package=python-pywcs).
Is there a specific reason to remove `CardList`? Pyfits itself is legacy only, and it would be nice if it would not break the API on its old days :-)
Feel free to just close this issue; in this case I would try to fix pywcs here (any help there would be appreciated, however ...)
Pywcs version in use is [1.12](https://pypi.python.org/pypi/pywcs).

**Comment by embray** [comment]
Probably pywcs should be pinned to PyFITS < 3.4 unless someone wants to make a new pywcs release too which I doubt.  But in any case that does complicate some things for which I apologized.

I had planned on releasing something called "PyFITS 4.0" which just has Astropy as a dependency and aliases "pyfits" to "astropy.io.fits".  I could do the same for pywcs.

**Comment by olebole** [comment]
There was such an attempt in the early days of astropy; this was however given up. I however also remember that it did not work to use them independently.
I anyway think that my solution is probably not soo complicated, since I can just replace `pyfits.CardList()` with Pythons `list()`, right? There is just one occurrence in the pywcs code.
So, the problem may probably not touch Debian users, but others still may be affected.

**Comment by embray** [comment]
I have come up with a way to do this using import hooks that is easy and should have no problems. Regardless, I don't know if or when I'll bother. 

So if you just want a quick patch for Debian I agree changing CardList() to just list() should suffice.
