### ISSUE TITLE
No code for getting number of extentions

### ISSUE THREAD

**Issue by pietrow** [spacetelescope/PyFITS#108]
There should be a way to get the number of extensions of a fits file, you'd expect HDUList to be able to do that. 

Something like this might be handy. 

```
def nextentions(im):
    '''
    Returns the number of extentions inside of a fits file.
    
    INPUT: im - filepath to fits file.
    OUTPUT: number of extentions in the file.    
    '''
    i = 0
    fit = pyfits.open(im)
    while True:
        try:
            trythis = fit[i].header

        except IndexError:
            fit.close()
            return i
        i+=1
```

**Comment by philhodge** [comment]
If you open the file like this:

import astropy.io.fits as fits
hdulist = fits.open(im)

then the total number of header/data units (including the primary) is 
len(hdulist), so the number of extensions is len(hdulist) - 1.

Phil

**Comment by mcara** [comment]
+1 @philhodge

**Comment by pllim** [comment]
@philhodge 's answer is the way to go.

By the way, PyFITS is deprecated. Please use `astropy.io.fits`. See http://astropy.readthedocs.org/en/stable/io/fits/index.html for details.
