### ISSUE TITLE
Can't update data in a fits table

### ISSUE THREAD

**Issue by csnap001** [spacetelescope/PyFITS#109]
I'm trying to update a .fits file and I keep getting the following error:

Traceback (most recent call last):

  File "<ipython-input-31-9c667a8986f9>", line 1, in <module>
    runfile('C:/Users/owner/Documents/.spyder2/fittingTest.py', wdir='C:/Users/owner/Documents/.spyder2')

  File "C:\Users\owner\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Users\owner\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/owner/Documents/.spyder2/fittingTest.py", line 854, in <module>
    fits.update('new.fits', Qname, 'sdss_name')

  File "C:\Users\owner\Anaconda2\lib\site-packages\astropy\io\fits\convenience.py", line 525, in update
    new_hdu = _makehdu(data, header)

  File "C:\Users\owner\Anaconda2\lib\site-packages\astropy\io\fits\convenience.py", line 772, in _makehdu
    hdu = ImageHDU(data)

  File "C:\Users\owner\Anaconda2\lib\site-packages\astropy\io\fits\hdu\image.py", line 1011, in __init__
    scale_back=scale_back)

  File "C:\Users\owner\Anaconda2\lib\site-packages\astropy\io\fits\hdu\image.py", line 138, in __init__
    self.data = data

  File "C:\Users\owner\Anaconda2\lib\site-packages\astropy\utils\decorators.py", line 526, in __set__
    ret = self.fset(obj, val)

  File "C:\Users\owner\Anaconda2\lib\site-packages\astropy\io\fits\hdu\image.py", line 236, in data
    self._bitpix = DTYPE2BITPIX[data.dtype.name]

KeyError: 'object'

I figured the issue was with the data type I set for Qname when I changed it to a numpy array. before it is a numpy array Qname's type is list where each element is a str type. I've tried setting the type for the numpy array to be np.str and str, but this returns the same error except that the last line is KeyError: 'String144' instead of what is above.  I don't think I understand what happens when you convert to a numpy array or what the dtype does, can anybody help?  I'm using python 2.7

**Comment by SaraOgaz** [comment]
hi @csnap001, could you give us an explicit example of the code you were trying to run when you got this error?

**Comment by csnap001** [comment]
sure:

\\\
c1 = fits.Column('sdss_name', format = 'A18', array = Qname)
c2 = fits.Column('Plate', format = 'J', array = Pl)
c3 = fits.Column('Fiber', format = 'J', array = Fib)
c4 = fits.Column('MJD', format = 'J', array = date)
c5 = fits.Column('OIIrew', format = 'D', array = OIIrew)
c6 = fits.Column('OIIfwhm', format = 'D', array = OIIfwhm)
c7 = fits.Column('OIIIrew', format = 'D', array = OIIIrew)
c8 = fits.Column('OIIIfwhm', format = 'D', array = OIIIfwhm)
c9 = fits.Column('z_dr7', format = 'D', array = reds)
c10 = fits.Column('ContPow', format = 'D', array = contPower)
c11 = fits.Column('OIIPow', format = 'D', array = OIIpower)
c12 = fits.Column('r', format = 'D', array = rMag)
c13 = fits.Column('g-i', format = 'D', array = giMag)
c14 = fits.Column('r-z', format = 'D', array = rzMag)

OIIrew = np.array(OIIrew, dtype = np.float64)
OIIfwhm = np.array(OIIfwhm, dtype = np.float64)
OIIIrew = np.array(OIIIrew, dtype = np.float64)
OIIIfwhm = np.array(OIIIfwhm, dtype = np.float64)
Qname = np.array(Qname, dtype = np.object_)
reds = np.array(reds, dtype = np.float64)
contPower = np.array(contPower, dtype = np.float64)
OIIpower = np.array(OIIpower, dtype = np.float64)
rMag = np.array(rMag, dtype = np.float64)
giMag = np.array(giMag, dtype = np.float64)
rzMag = np.array(rzMag, dtype = np.float64)
Pl = np.array(Pl, dtype = np.string_)
Fib = np.array(Fib, dtype = np.string_)
date = np.array(date, dtype = np.string_)

if(not(path.exists('new.fits'))):
    newhdu = fits.new_table([c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14])
    newhdu.writeto('new.fits')
else:
    fits.open('new.fits')
    fits.update('new.fits', Qname, 'sdss_name')
    fits.update('new.fits', Pl, 'Plate')
    fits.update('new.fits', Fib, 'Fiber')
    fits.update('new.fits', date, 'MJD')
    fits.update('new.fits', OIIrew, 'OIIrew')
    fits.update('new.fits', OIIfwhm, 'OIIfwhm')
    fits.update('new.fits', OIIIrew, 'OIIIrew')
    fits.update('new.fits', OIIIfwhm, 'OIIIfwhm')
    fits.update('new.fits', reds, 'z_dr7')
    fits.update('new.fits', contPower, 'ContPow')
    fits.update('new.fits', OIIpower, 'OIIPow')
    fits.update('new.fits', rMag, 'r')
    fits.update('new.fits', giMag, 'g-i')
    fits.update('new.fits', rzMag, 'r-z')
    fits.flush()
    fits.close()

all of the objects are lists that I'm trying to convert to numpy arrays.  let me know if this is not enough information.  The project I'm working on is fairly large and the error only occurs when I have this bit of code, so I figure the error is in here somewhere.

**Comment by pllim** [comment]
Specifically:

1. How was `fits` defined? Is it a module, a file pointer, etc?
2. What is the actual content of `Qname`? 
3. What is your PyFITS version? Do you also have Astropy installed?

**Comment by pllim** [comment]
Oh wait... In your traceback, you are actually using `astropy.io.fits`. This is not the right place to report your problem. Please open a new issue at https://github.com/astropy/astropy/issues . We can all continue over there.
