### ISSUE TITLE
Memory leak in compressionmodule.c ?

### ISSUE THREAD

**Issue by PierreAstier** [spacetelescope/PyFITS#110]
For a CCD test bench, we are using some pyfits code writing MEF files with 16 RICE-compressed BITPIX=32 extensions. The memory footprint of the python executable grows with the number of written images, until we either stop or crash.

We launched the python process under valgrind supervision, which reported MB-sized chunks of unfreed memory allocated  via a call to realloc in pyfits compressionmodule.c source file.

I was able to reproduce the memory usage increase with the following small code:

```
import pyfits as pf
import numpy as np
import sys


next=16
num = 100
try :
    num = int(sys.argv[1])
except:
    pass
for count in range(num) :
    l = pf.HDUList()
    for i in range(next) :
        data = np.array(np.random.random([500,2000])*1000,dtype=np.int32)
        l.append(pf.CompImageHDU(data=data))
    l.writeto('toto_%d.fits'%count,clobber=True)
    l.close()

```

Inspecting the compressionmodule.c code,  I realized that the allocated memory is handed over to some PyArray constructor (at line 944 in pyfits version 3.4):

`tmp = (PyArrayObject*) PyArray_SimpleNewFromData(1, &znaxis, NPY_UBYTE,
                                                     outbuf);`

This [post](http://stackoverflow.com/questions/27912483/memory-leak-in-python-extension-when-array-is-created-with-pyarray-simplenewfrom) on stackoverflow reports a similar problem and makes it pretty clear (referring to scipy documentation) that, by default, "PyArray_SimpleNewFromData" will _not_ free the memory it received. To change the default behavior, the same post suggests something like:

`tmp->flags |=  NPY_ARRAY_OWNDATA;`

which I added at line 947 of compressionmodule.c . The small piece of python above can now run forever as well as our test bench. I am not sure if this is the right thing to do, but it actually fixed our problem.

**Comment by pllim** [comment]
@PierreAstier , thank you for the report. PyFITS is deprecated. Please use [astropy.io.fits](http://docs.astropy.org/en/stable/io/fits/).

As far as the piece of code is concerned, it looks pretty much the same over there as well. However, there is a chance the problem has been fixed in another way. If you still see the same problem using Astropy, you are very welcome to open a pull request with your suggested fix so others may benefit from it. Please see http://docs.astropy.org/en/latest/development/workflow/development_workflow.html for instructions.

**Comment by PierreAstier** [comment]
We faced the problem using astropy.io.fits. We switched to pyfits to study and eventually resolve the issue.  With the head git version of astropy, the problem shows us in exactly the same way. However,
turning the right flag depends on the numpy version used, and I do not know how to write it properly
for versions of numpy before and after 1.7.

For numpy above 1.7, the fix now reads : 

```
diff --git a/astropy/io/fits/src/compressionmodule.c b/astropy/io/fits/src/compressionmodule.c
index 29773df..4b7f76d 100644
--- a/astropy/io/fits/src/compressionmodule.c
+++ b/astropy/io/fits/src/compressionmodule.c
@@ -963,6 +963,9 @@ PyObject* compression_compress_hdu(PyObject* self, PyObject* args)
     tmp = (PyArrayObject*) PyArray_SimpleNewFromData(1, &znaxis, NPY_UBYTE,
                                                      outbuf);
 
+    // old parlance:
+    //tmp->flags |= NPY_ARRAY_OWNDATA;
+    PyArray_ENABLEFLAGS(tmp, NPY_ARRAY_OWNDATA);
 
     // Leaves refcount of tmp untouched, so its refcount should remain as 1
     retval = Py_BuildValue("KN", heapsize, tmp);
```

So, I don't know how to test it properly for two different versions of numpy.  However, the fix is again effective against what looks like a memory leak.

**Comment by MSeifert04** [comment]
@PierreAstier At least for the astropy 1.2 series (current master) this shouldn't be a problem because numpy > 1.7 is already a requirement there.  👍

**Comment by pllim** [comment]
For simplicity, on the Astropy side, we can just accept the Numpy >= 1.7 solution (what works for Numpy > 1.7 also works for Numpy == 1.7, right?) and milestone it to 1.2.2 instead of 1.0.x.

**Comment by embray** [comment]
Please open a ticket for this on the Astropy issue tracker.

**Comment by pllim** [comment]
Done. See astropy/astropy#5399 and let's move any future discussions over there.
