### ISSUE TITLE
pyfits install error maximum recursion depth exceeded

### ISSUE THREAD

**Issue by petacube** [spacetelescope/PyFITS#114]
platform macos high sierra
python anaconda 3.5

python setup.py build

Installed /private/var/folders/nc/4fm6m_fd3t79jz6qyp6bhpjm0000gn/T/easy_install-p_1fete8/stsci.distutils-0.3.7/.eggs/d2to1-0.2.12.post1-py3.5.egg

Installed /private/tmp/PyFITS/.eggs/stsci.distutils-0.3.7-py3.5.egg
Searching for d2to1>=0.2.12
Reading https://pypi.python.org/simple/d2to1/
Downloading https://pypi.python.org/packages/dc/bd/eac45e4e77d76f6c0ae539819c40f1babb891d7855129663e37957a7c2df/d2to1-0.2.12.post1.tar.gz#md5=1ba7e64ead23cbf104993122f0871030
Best match: d2to1 0.2.12.post1
Processing d2to1-0.2.12.post1.tar.gz
Writing /var/folders/nc/4fm6m_fd3t79jz6qyp6bhpjm0000gn/T/easy_install-uev2ul17/d2to1-0.2.12.post1/setup.cfg
Running d2to1-0.2.12.post1/setup.py -q bdist_egg --dist-dir /var/folders/nc/4fm6m_fd3t79jz6qyp6bhpjm0000gn/T/easy_install-uev2ul17/d2to1-0.2.12.post1/egg-dist-tmp-mnns4r9a
creating /private/tmp/PyFITS/.eggs/d2to1-0.2.12.post1-py3.5.egg
Extracting d2to1-0.2.12.post1-py3.5.egg to /private/tmp/PyFITS/.eggs

Installed /private/tmp/PyFITS/.eggs/d2to1-0.2.12.post1-py3.5.egg
error in setup command: Error parsing /private/tmp/PyFITS/setup.cfg: RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by pllim** [comment]
Hi. Thank you for your interest in PyFITS. Unfortunately, it is deprecated and no longer actively supported. Please use `astropy.io.fits` (see http://www.astropy.org/) instead.

**Comment by petacube** [comment]
aha, thanks a lot!! i had migrated code to astropy.io <http://astropy.io/>.fits and it was painless migration

Stanislav

**Comment by pllim** [comment]
Great to hear! Thank you for letting us know.
