### ISSUE TITLE
PyFITS does not interact well with multiprocess and/or matplotlib

### ISSUE THREAD

**Issue by adamamiller** [spacetelescope/PyFITS#38]
I have been having trouble getting matplotlib figures to save within a process generated by multiprocessing. Today I discovered that this problem only occurs if I have attempted to import pyfits. Here is a piece of test code that behaves as expected and produces a file called testfig.png:

```
    from multiprocessing import Process
    # import pyfits

    def makeplot(a,b):
        import matplotlib.pyplot as plt
        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.plot(a,b,'o')
        fig.savefig('testfig.png')
        plt.close()
        return None

    p = Process(target = makeplot, args = ([1,2,3,4], [5,6,7,8]))
    p.daemon = True
    p.start()
    p.join()
```

If I uncomment the import of pyfits, however, a figure is no longer produced and saved by this same piece of test code. Are there known reasons why pyfits changes the expected behavior of multiprocessing and/or matplotlib?

**Comment by ionox0** [comment]
@mdboom This helped me with an issue that I thought was related to OpenCV with multiprocessing. https://github.com/opencv/opencv/issues/5150 - Much appreciated.
