### ISSUE TITLE
boolean mask issue with FITS_rec created using from_columns ()

### ISSUE THREAD

**Issue by mauriceleutenegger** [spacetelescope/PyFITS#99]
Suppose I want to merge two FITS_rec that have identical dtype, and then do a normal boolean mask operation on that :

```
import pyfits as pf
data1 = pf.getdata (myfile, 1)
data2 = pf.getdata (myfile, 2)
nrows = data1.size + data2.size
mergeddata = pf.FITS_rec.from_columns (data1, nrows=nrows)
mergeddata[data1.size:] = data2
mymask = (mergeddata.field ('myfield') > somecriterion)
maskeddata = mergeddata [mymask]
```

This gives an error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mleutene/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyfits/fitsrec.py", line 496, in __getitem__
    arrays.append(self._coldefs._arrays[idx][key])
ValueError: too many boolean indices
```

If I limit the number of values in the mask to the number of rows in the first of the two merging tables, the error message goes away, even though the size of the merged FITS_rec is the same as the size of the mask:

```
maskeddata = mergeddata [mymask[:data1.size]]
```

This implies that somehow the new FITS_rec created using from_columns () remembers the size of the parent FITS_rec, even though its size is the expected sum of the sizes of the two FITS_recs that were merged.

**Comment by embray** [comment]
Thanks for the report.  I agree, that sounds like a bug.  

In the meantime, is there any reason you can't use Astropy's [Table](http://docs.astropy.org/en/stable/table/index.html) interface?  For most of these kinds of operations it is far more convenient and less kludgy.

**Comment by mauriceleutenegger** [comment]
I've never tried Table, but will give it a shot. Thanks for the suggestion!

**Comment by embray** [comment]
PyFITS hasn't been updated in a while, though I need to do that.  There are a number of fixes in Astropy that haven't been ported back to PyFITS yet (this however does not appear to be one of them).

**Comment by embray** [comment]
Also, for what it's worth, here's an example of appending a table using Astropy Table:

```python

from astropy.table import Table, vstack

data1 = Table.read(filename, hdu=1)
data2 = Table.read(filename, hdu=2)
data3 = vstack((data1, data2))
masked_data = data3[data3[colname] > 1]
```

all the masking and such should work as expected.

**Comment by embray** [comment]
I think I've fixed the underlying issue (or at least provided a workaround for now) in astropy/astropy#3641, and will try to include this in the next bugfix release for pyfits.

Regardless, I highly recommend using the Astropy Table interface for these kinds of basic table manipulations, where possible.

**Comment by mauriceleutenegger** [comment]
Great, thanks!

I was able to get the functionality I was looking for with astropy.table.
Thanks for the suggestion!
